### ISSUE TITLE
Crash on Flipwalkers

### ISSUE THREAD

**Issue by ZeldaZach** [aeosynth/spoiler#1]
After testing with your built, it seems as if when a flipwalker is created, your database causes the client to crash and become unrecoverable until the server is restarted or the room times out.

I have pinpointed the issue to the `<pt>` tag, for which walkers you signify with a number (i.e. "1", "5", etc.)

The `<pt>` tag **_must**_ be in the format of `N/N` where N is any integer. With the walkers, they are in the incorrect format and are thus causing issues. 

The fix suggested is to just remove the `<pt>` tag from all planeswalkers. Users usually add the custom counters (the red, green, and yellow ones) manually once they play a planeswalker to signify loyalty.

This is a critical issue and should be addressed as soon as possible.

**Comment by aeosynth** [comment]
fixed. also lol.

**Comment by ZeldaZach** [comment]
Impressive response time. Thanks!

Are you going to update the gist you host as well?

**Comment by aeosynth** [comment]
done. i wasn't sure people were even using this. are you going to fix this on the cock side?

**Comment by ZeldaZach** [comment]
Cockatrice has built in ways to avoid the pt tag from being out of form. Loading a custom document outside of the oracle tool can always lead to problems, which is why we usually suggest you don't do it unless you know what you're doing.

If you have any suggested fixes, feel free to ticket them and I'll get to it

**Comment by ZeldaZach** [comment]
Also, two small things (that don't impact anything, but still are good to have) is you have an extra > after the name (`<name>Name Here</name>>`) and you should include a `<tablerow>`tag ([more info found here about the tablerow tag](https://github.com/Cockatrice/Cockatrice/wiki/Custom-Card-Images#follow-the-steps-if-youd-like-to-add-your-own-custom-cards-to-cockatrice))

**Comment by aeosynth** [comment]
updated
