### ISSUE TITLE
Devoid not supported.

### ISSUE THREAD

**Issue by Psithief** [aeosynth/spoiler#2]
Assuming Devoid returns in the next set, perhaps fix the `<color>` tag for cards with Devoid?

**Comment by aeosynth** [comment]
fixed

**Comment by Psithief** [comment]
I'll reiterate from Zach:

> Impressive response time. Thanks!
> 
> Are you going to update the gist you host as well?

Oh, you already did. :grin:

**Comment by aeosynth** [comment]
:heart:

**Comment by aeosynth** [comment]
my users want devoid cards treated as colored when deckbuilding

**Comment by Psithief** [comment]
Are those users using Cockatrice for their deckbuilding? 

:suspect: 
If they are, I think that's a failure with the program that's just going to re-emerge once the normal cards update comes.

**Comment by aeosynth** [comment]
i [asked](http://www.mtgsalvation.com/forums/magic-fundamentals/digital-magic-and-mtg-software/494332-mtg-json-new-website-provides-mtg-card-data-in?comment=527) the mtgjson guy about adding a 'color identity' key, and i implemented that for the spoilers

**Comment by Psithief** [comment]
He had an issue open for it @ Sembiance/mtgjson/issues/45

**Comment by aeosynth** [comment]
yeah i was lazy. thanks for the heads up
