### ISSUE TITLE
BFZ spoiler output oddities.

### ISSUE THREAD

**Issue by Psithief** [aeosynth/spoiler#3]
1. Your type line separates types from subtypes with a hyphen instead of an em dash. `Creature — Human Warrior` is correct, `Creature - Human Warrior` is not.
2. Grip of Desolation has `<pt>/</pt>` and type `Intant` instead of `Instant`. Perhaps you could add a sanity check against all known card types for typos in the spoiler feed?

**Comment by aeosynth** [comment]
> `Creature — Human Warrior` is correct, `Creature - Human Warrior` is not.

define `correct`

> sanity check

added a check for pt. i'm not sure how far this should go wrt error correction. spoilers are going to have bugs.

**Comment by Psithief** [comment]
`correct`:
- As printed on cards
- As used in [Gatherer](http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid=398431)

**Comment by aeosynth** [comment]
fixed. closing, the `Intant` issue is `WONTFIX`

**Comment by aeosynth** [comment]
ok so i did fix `Intant`
